#!/usr/bin/env ruby

Dir[File.dirname(__FILE__) + '/lib/*.rb'].each {|file| require file }

#Reading and writing to file
input_file = ARGV[0]
output_file = ARGV[1]

file_processor = FileProcessor.new(input_file, output_file)

str = file_processor.read_file

parsed_string = PathParser.new(str)

mapper = PointMapper.new(parsed_string)

points = mapper.get_points

writer = PathWriter.new

str_with_path = writer.write(str, points)
 

file_processor.write_file(str_with_path)