#!/usr/bin/env ruby
Dir[File.dirname(__FILE__) + '/lib/*.rb'].each {|file| require file }

input_file = ARGV[0]
output_file = ARGV[1]

pather = Pather.new(input_file, output_file)

pather.show_the_way